#!/bin/sh
# Copyright 2020 Collabora Ltd.
# SPDX-License-Identifier: LGPL-2.1-or-later

set -eux

if [ -n "${AUTOPKGTEST_ARTIFACTS-}" ]; then
	WORKDIR="$AUTOPKGTEST_ARTIFACTS"
else
	WORKDIR="$(mktemp -d)"
	trap 'cd /; rm -fr "$WORKDIR"' 0 INT QUIT ABRT PIPE TERM
fi

if [ -n "${DEB_HOST_GNU_TYPE:-}" ]; then
    CROSS_COMPILE="$DEB_HOST_GNU_TYPE-"
else
    CROSS_COMPILE=
fi

cp examples/make_sine.c "$WORKDIR"
cd "$WORKDIR"

# Deliberately word-splitting pkgconf's output:
# shellcheck disable=SC2046
"${CROSS_COMPILE}gcc" -omake_sine make_sine.c -lm $("${CROSS_COMPILE}pkgconf" --cflags --libs sndfile)
./make_sine
